<?php

namespace NAO\MapBundle\Repository;

/**
 * EditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditRepository extends \Doctrine\ORM\EntityRepository
{
}
