easy_admin:
    site_name: 'Nos Amis les Oiseaux'
    design:
        brand_color: '#707070'
        color_scheme: 'light'
        menu:
            - { label: 'Le site', route: 'homepage', icon: 'home' }
            - label: 'Fiches et Observations'
              icon: 'file'
              children:
                - { entity: 'Bird', label: 'Fiches oiseaux' }
                - { entity: 'Observation', label: 'Observations' }
            - label: 'Blog'
              icon: 'sticky-note'
              children:
                - { entity: 'Article', label: 'Articles' }
                - { entity: 'Comment', label: 'Commentaires' }
            - { entity: 'User', label: 'Utilisateurs', icon: 'user' }

    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    list:
        actions:
            - { name: 'edit', icon: 'pencil', label: '', title: 'Éditer' }
            - { name: 'delete', icon: 'trash', label: '', title: 'Supprimer' }
    entities:

        Bird:
            class: NAO\FicheBundle\Entity\Bird
            list:
                actions:
                    - { name: 'edit', icon: 'pencil', label: '', title: 'Éditer' }
                    - { name: 'new', label: 'Créer une fiche'}
                title: Les fiches oiseaux
                sort: ['id', 'ASC']
                fields: 
                    - { property: 'id', label: "Numéro de la fiche" }
                    - { property: 'taxref.valid_name', label: "Nom de l'oiseau" }
                    - { property: 'taxref.familia', label: "Famille" }
                    - { property: 'size',  label: 'Taille' }
                    - { property: 'weight',  label: 'Poids' }
                    - { property: 'color',  label: 'Principal Couleur' }
                    - { property: 'feature',  label: 'Information complémentaire' }
                    - { property: 'naturalist',  label: 'Naturalist Validation' }
                    - { property: 'status',  label: 'Validation' }
            form:
                fields:
                    - { property: 'size',  label: 'Taille' }
                    - { property: 'weight',  label: 'Poids' }
                    - { property: 'color',  label: 'Principal Couleur' }
                    - { property: 'feature',  label: 'Information complémentaire' }
                    - { property: 'naturalist',  label: 'Naturalist Validation' }
                    - { property: 'status',  label: 'Validation', help: '0 = en Attente, 1 = Valider, 2 = Refuser, 4 = Broullions' }
                    
            new:
                title:  'Créer une fiche'
            edit:
                title:  'Modifier la fiche'

        Observation:
            class: NAO\MapBundle\Entity\Observation
            list:
                actions:
                    - { name: 'edit', icon: 'pencil', label: '', title: 'Éditer' }
                title: Les observations
                sort: ['id', 'ASC']
                fields: 
                    - { property: 'taxref.valid_name', label: "Nom de l'oiseau" }
                    - { property: 'user', label: 'Auteur' }
                    - { property: 'watched', label: 'Date' }
                    - { property: 'place', label: 'Lieu' }
                    - { property: 'comments', label: 'Description' }
                    - { property: 'individuals',  label: 'Nombre aperçu' }
                    - { property: 'naturalist',  label: 'Naturalist Validation' }
                    - { property: 'status',  label: 'Validation' }
            edit:
                title:  'Modifier la fiche'
                fields:
                    - { property: 'user', label: 'Auteur' }
                    - { property: 'watched', label: 'Date' }
                    - { property: 'place', label: 'Lieu', help: 'Ville (département) ex: Paris (75)' }
                    - { property: 'comments', label: 'Description' }
                    - { property: 'individuals',  label: 'Nombre aperçu' }
                    - { property: 'naturalist',  label: 'Naturalist Validation' }
                    - { property: 'status',  label: 'Validation', help: '0 = en Attente, 1 = Valider, 2 = Refuser, 4 = Broullions' }
        Article:
            class: NAO\BlogBundle\Entity\Article
            list:
                actions:
                    - { name: 'edit', icon: 'pencil', label: '', title: 'Éditer' }
                    - { name: 'new', label: 'Créer un article'}
                title: Les articles
                sort: ['id', 'ASC']
                fields: 
                    - { property: 'title', label: 'Titre' }
                    - { property: 'user', label: 'Auteur' }
                    - { property: 'date',  label: 'Date' }
                    - { property: 'moderation',  label: 'Publié' }
            edit:
                title:  "Modifier l'article"
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'date',  label: 'Date' }
                    - { property: 'content',  label: 'Contenu' }
                    - { property: 'image',  label: 'Image' }
            new:
                title:  "Créer un article"
                fields:
                    - { property: 'title', label: 'Titre' }
                    - { property: 'date',  label: 'Date' }
                    - { property: 'user', label: 'Auteur', help: "Choississez l'auteur" }
                    - { property: 'content',  label: 'Contenu' }
                    - { property: 'image',  label: 'Image' }
                    - { property: 'moderation',  label: 'Publié' }
        Comment:
            class: NAO\BlogBundle\Entity\Comment
            list:
                actions:
                    - { name: 'edit', icon: 'pencil', label: '', title: 'Éditer' }
                    - '-new'
                    - '-search'
                title: Les commentaires
                sort: ['id', 'ASC']
                fields: 
                    - { property: 'user', label: 'Auteur' }
                    - { property: 'date', label: 'Date' }
                    - { property: 'content',  label: 'Contenu' }
                    - { property: 'article',  label: 'Article correspondant' }
                    - { property: 'moderation',  label: 'Publié' }
            edit:
                title:  'Modérer le commentaire'
                fields:
                    - { property: 'content',  label: 'Contenu' }
                    # - { property: 'date', label: 'Date' }
                    - { property: 'moderation',  label: 'Publié' }
        User:
            class: NAO\UserBundle\Entity\User
            list:
                actions:
                    - { name: 'edit', icon: 'pencil', label: '', title: 'Éditer' }
                    - { name: 'new', label: 'Créer un compte' }
                title: Les utilisateurs
                sort: ['id', 'ASC']
                fields: 
                    - id
                    - { property: 'username', label: 'Pseudo' }
                    - { property: 'lastname', label: 'Nom' }
                    - { property: 'firstname', label: 'Prénom' }
                    - { property: 'email', label: 'Contact', type: 'email' }
                    - { property: 'town', label: 'Ville' }
                    - { property: 'newsletter',  type: 'boolean' }
                    - { property: 'roles', label: 'Rôle' }
                    - { property: 'points', label: 'Nbr de points' }
                    - { property: 'enabled',  label: 'Actif' }
            edit:
                title:  'Modifier le compte utilisateur'
                fields:
                    - { property: 'lastname', label: 'Nom' }
                    - { property: 'firstname', label: 'Prénom' }
                    - { property: 'username', label: 'Pseudo' }
                    - { property: 'email', label: 'Contact', type: 'email' }
                    - { property: 'town', label: 'Ville' }
                    - { property: 'newsletter' }
                    - { property: 'roles', label: 'Rôle', help: 'ROLE_USER (Particulier) ou ROLE_ADMIN (Naturaliste)' }
                    - { property: 'points', label: 'Nbr de points' }
                    - { property: 'enabled',  label: 'Activation du compte' }
            new:
                title:  'Créer un compte'
                fields:
                    - { property: 'lastname', label: 'Nom' }
                    - { property: 'firstname', label: 'Prénom' }
                    - { property: 'username', label: 'Pseudo' }
                    - { property: 'email', label: 'Email', type: 'email' }
                    - { property: 'town', label: 'Ville' }
                    - { property: 'rgpd',  label: 'RGPD' }
                    - { property: 'newsletter' }
                    - { property: 'roles', label: 'Rôle', help: 'ROLE_USER (Particulier) ou ROLE_ADMIN (Naturaliste)' }
                    - { property: 'enabled',  label: 'Activation du compte' }
                    - { property: 'plainPassword',  label: 'Mot de passe' }
                    - { property: 'password',  label: 'Répétez le mot de passe' }
