nao_fiche:
    resource: "@NAOFicheBundle/Controller/"
    type:     annotation

nao_user:
    resource: "@NAOUserBundle/Controller/"
    type:     annotation

nao_game:
    resource: "@NAOGameBundle/Controller/"
    type:     annotation

nao_map:
    resource: "@NAOMapBundle/Controller/"
    type:     annotation

nao_blog:
    resource: "@NAOBlogBundle/Controller/"
    type:     annotation

nao_core:
    resource: "@NAOCoreBundle/Controller/"
    type:     annotation



easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api_login_check:
    path: /API/login_check

