nao_game:
    resource: "@NAOGameBundle/Resources/config/routing.yml"
    prefix:   /game

nao_map:
    resource: "@NAOMapBundle/Resources/config/routing.yml"
    prefix:   /map

nao_blog:
    resource: "@NAOBlogBundle/Resources/config/routing.yml"
    prefix:   /blog

nao_core:
    resource: "@NAOCoreBundle/Resources/config/routing.yml"
    prefix:   /core

app:
    resource: '@AppBundle/Controller/'
    type: annotation

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin
